// User reducer
export const SET_USER_IS_LOGGED_IN = "SET_USER_IS_LOGGED_IN";
export const ADD_TO_FAVORITES_LIST = "ADD_TO_FAVORITES_LIST";
export const REMOVE_FROM_FAVORITES_LIST = "REMOVE_FROM_FAVORITES_LIST";
export const ADD_TO_CUSTOM_LIST = "ADD_TO_CUSTOM_LIST";
export const REMOVE_FROM_CUSTOM_LIST = "REMOVE_FROM_CUSTOM_LIST";
export const GET_BUSINESS_INFO_AND_UPDATE = "GET_BUSINESS_INFO_AND_UPDATE";
export const GET_USER_FAVORITES_LIST = "GET_USER_FAVORITES_LIST";
export const CLEAR_FAVORITES_LIST = "CLEAR_FAVORITES_LIST";

// Search reducer
export const SEARCH_BUSINESSES_YELP = "SEARCH_BUSINESSES_YELP";
export const UPDATE_SEARCH_TERM_AND_LOCATION = "UPDATE_SEARCH_TERM_AND_LOCATION";
export const UPDATE_OFFSET = "UPDATE_OFFSET";
export const UPDATE_SEARCH_RESULTS = "UPDATE_SEARCH_RESULTS";
export const UPDATE_PARAMS_HAS_NO_RESULTS = "UPDATE_PARAMS_HAS_NO_RESULTS";

// Map reducer
export const UPDATE_BUSINESS_ON_MAP = "UPDATE_BUSINESS_ON_MAP";
export const SWTICH_TO_GOOGLE_MAPS = "SWTICH_TO_GOOGLE_MAPS";

// Favorites list reducer
export const UPDATE_FAVORITES_LIST_CURRENT_PAGE = "UPDATE_CURRENT_PAGE";
export const UPDATE_FAVORITES_LIST_TOTAL_PAGES = "UPDATE_TOTAL_PAGES";

// Random business reducer
export const UPDATE_RANDOM_BUSINESS = "UPDATE_RANDOM_BUSINESS";
export const GET_BUSINESSES_WITHIN_LIMIT = "GET_BUSINESSES_WITHIN_LIMIT";
export const UPDATE_CURRENT_RANDOM_LIST = "UPDATE_CURRENT_RANDOM_LIST"; 
