// User reducer
export const SET_USER_IS_LOGGED_IN = "SET_USER_IS_LOGGED_IN";

// Search reducer
export const SEARCH_BUSINESSES_YELP = "SEARCH_BUSINESSES_YELP";
export const UPDATE_SEARCH_TERM_AND_LOCATION = "UPDATE_SEARCH_TERM_AND_LOCATION";
