// User reducer
export const SET_USER_IS_LOGGED_IN = "SET_USER_IS_LOGGED_IN";
export const ADD_TO_FAVORITES_LIST = "ADD_TO_FAVORITES_LIST";
export const REMOVE_FROM_FAVORITES_LIST = "REMOVE_FROM_FAVORITES_LIST";
export const ADD_TO_CUSTOM_LIST = "ADD_TO_CUSTOM_LIST";
export const REMOVE_FROM_CUSTOM_LIST = "REMOVE_FROM_CUSTOM_LIST";
export const GET_BUSINESS_INFO_AND_UPDATE = "GET_BUSINESS_INFO_AND_UPDATE";

// Search reducer
export const SEARCH_BUSINESSES_YELP = "SEARCH_BUSINESSES_YELP";
export const UPDATE_SEARCH_TERM_AND_LOCATION = "UPDATE_SEARCH_TERM_AND_LOCATION";
export const UPDATE_OFFSET = "UPDATE_OFFSET";

// Map reducer
export const UPDATE_BUSINESS_ON_MAP = "UPDATE_BUSINESS_ON_MAP";
export const SWTICH_TO_GOOGLE_MAPS = "SWTICH_TO_GOOGLE_MAPS";

// Favorites list reducer
export const UPDATE_FAVORITES_LIST_CURRENT_PAGE = "UPDATE_CURRENT_PAGE";
export const UPDATE_FAVORITES_LIST_TOTAL_PAGES = "UPDATE_TOTAL_PAGES";
